In [1]:
import psycopg2
import pandas as pd

# dummy info
conn = psycopg2.connect(
    dbname = 'ds202',
    user = 'admin',
    password = 'admin',
    host = 'localhost',
    port = '5432' )

In [2]:
cur = conn.cursor()
query = "SELECT * FROM departments LIMIT 10;"
df_departments = pd.read_sql_query(query, conn)
df_departments

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/3950170051.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_departments = pd.read_sql_query(query, conn)

   department_id   department_name   location  budget
0              1             Sales     Berlin  489088
1              2         Marketing      Tokyo  313046
2              3       Engineering   New York  205947
3              4                HR  Vancouver  388543
4              5           Finance     Berlin  228177
5              6                IT     London  316454
6              7        Operations     London  209575
7              8  Customer Service     Berlin  473048
8              9             Legal     London  307606
9             10               R&D      Tokyo  392822

In [3]:
cur = conn.cursor()
query = "SELECT * FROM employees LIMIT 10;"
df_employees = pd.read_sql_query(query, conn)
df_employees

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/1925710423.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_employees = pd.read_sql_query(query, conn)

,employee_id,first_name,last_name,department_id,manager_id,salary,hire_date
0,1,John,Clark,6.0,NaN,87362,2021-03-30
1,2,Mike,Garcia,2.0,4.0,60128,2019-02-08
2,3,Chris,Johnson,6.0,10.0,99383,2017-12-29
3,4,Anna,Brown,NaN,3.0,105545,2017-02-10
4,5,Sara,Williams,2.0,9.0,49865,2018-10-11
5,6,John,Williams,NaN,13.0,42219,2012-03-25
6,7,David,Martinez,NaN,18.0,79809,2010-12-12
7,8,Anna,Clark,NaN,15.0,45287,2016-06-07
8,9,John,Smith,2.0,4.0,74387,2010-12-29
9,10,John,Garcia,NaN,15.0,48512,2016-09-09

# 1 INNER JOIN
Select employee names, salaries, and their respective department names. Only include employees assigned to a department.

In [4]:
query = """
SELECT first_name, last_name, salary, departments.department_name
FROM employees
JOIN departments ON employees.department_id = departments.department_id;
"""

df = pd.read_sql_query(query, conn)
df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/2049150049.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

   first_name last_name  salary   department_name
0        John     Clark   87362                IT
1        Mike    Garcia   60128         Marketing
2       Chris   Johnson   99383                IT
3        Sara  Williams   49865         Marketing
4        John     Smith   74387         Marketing
5       Linda     Smith   41342                IT
6        John   Johnson  103076             Sales
7       Chris  Martinez  119767               R&D
8        Anna  Williams   82078           Finance
9       Chris   Johnson   52219                HR
10      Linda  Martinez   40235               R&D
11      Chris    Garcia  107444               R&D
12      Linda     Smith  105441           Finance
13       Sara  Williams  113698         Marketing
14      Chris     Smith   45415                IT
15       Mike   Johnson   76159         Marketing
16       John  Williams   60611  Customer Service
17       Sara  Martinez   56984                HR
18      David  Williams   54060  Customer Service
19      David    Garcia   83303                HR
20       John     Brown   99207       Engineering
21      Chris  Williams  115046       Engineering
22      Linda  Williams  113340           Finance
23       John   Johnson  111520               R&D
24       Mike     Brown   58574                IT
25       Anna     Smith   49184             Sales
26       Jane  Williams   59096           Finance
27      Linda    Garcia  107728             Legal
28       Sara     Smith   85558         Marketing
29      Chris       Lee   51302             Legal
30      Linda   Johnson  111324                HR
31       Jane       Lee   45408             Sales
32       Anna  Martinez   99379  Customer Service
33       Anna  Martinez   49446       Engineering
34       Mike     Brown  104484         Marketing
35       John     Smith   59029        Operations
36       John    Garcia   99201       Engineering
37      Chris     Smith  111907                IT
38       Sara     Clark  111895       Engineering
39       Sara  Martinez   60103           Finance
40       Jane  Martinez  104772               R&D
41       Mike  Williams   54382        Operations
42      Chris    Garcia   60609        Operations

# 2 LEFT JOIN
List all employees along with their department names. Show 'Unassigned' for employees without a department

In [5]:
query = """
SELECT first_name, last_name, 
CASE WHEN departments.department_name is null THEN 'Unaasined'
ELSE departments.department_name END
FROM employees
LEFT JOIN departments ON employees.department_id = departments.department_id;
"""

df = pd.read_sql_query(query, conn)
df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/2496123193.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

   first_name last_name department_name
0        John     Clark              IT
1        Mike    Garcia       Marketing
2       Chris   Johnson              IT
3        Anna     Brown       Unaasined
4        Sara  Williams       Marketing
..        ...       ...             ...
95      Chris    Garcia      Operations
96      David   Johnson       Unaasined
97       John     Brown       Unaasined
98       Jane     Brown       Unaasined
99       Jane  Martinez       Unaasined

[100 rows x 3 columns]

# 3 RIGHT JOIN
Display each department name along with employee names. Include departments that have no employees.

In [41]:
query = """
SELECT
    departments.department_name, first_name, last_name
FROM
    employees
RIGHT JOIN
    departments 
ON
    employees.department_id = departments.department_id;
"""

df = pd.read_sql_query(query, conn)
df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/2397058825.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

     department_name first_name last_name
0                 IT       John     Clark
1          Marketing       Mike    Garcia
2                 IT      Chris   Johnson
3          Marketing       Sara  Williams
4          Marketing       John     Smith
5                 IT      Linda     Smith
6              Sales       John   Johnson
7                R&D      Chris  Martinez
8            Finance       Anna  Williams
9                 HR      Chris   Johnson
10               R&D      Linda  Martinez
11               R&D      Chris    Garcia
12           Finance      Linda     Smith
13         Marketing       Sara  Williams
14                IT      Chris     Smith
15         Marketing       Mike   Johnson
16  Customer Service       John  Williams
17                HR       Sara  Martinez
18  Customer Service      David  Williams
19                HR      David    Garcia
20       Engineering       John     Brown
21       Engineering      Chris  Williams
22           Finance      Linda  Williams
23               R&D       John   Johnson
24                IT       Mike     Brown
25             Sales       Anna     Smith
26           Finance       Jane  Williams
27             Legal      Linda    Garcia
28         Marketing       Sara     Smith
29             Legal      Chris       Lee
30                HR      Linda   Johnson
31             Sales       Jane       Lee
32  Customer Service       Anna  Martinez
33       Engineering       Anna  Martinez
34         Marketing       Mike     Brown
35        Operations       John     Smith
36       Engineering       John    Garcia
37                IT      Chris     Smith
38       Engineering       Sara     Clark
39           Finance       Sara  Martinez
40               R&D       Jane  Martinez
41        Operations       Mike  Williams
42        Operations      Chris    Garcia

# 4 FULL OUTER JOIN
Select all employees and all departments, including employees without departments and departments without employees.

In [ ]:
query = """
SELECT
    departments.department_name, first_name, last_name
FROM
    employees
FULL OUTER JOIN
    departments 
ON 
    employees.department_id = departments.department_id;
"""

df = pd.read_sql_query(query, conn)
# pd.set_option('display.max_rows', None)

df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/1007628122.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

   department_name first_name last_name
0               IT       John     Clark
1        Marketing       Mike    Garcia
2               IT      Chris   Johnson
3             None       Anna     Brown
4        Marketing       Sara  Williams
..             ...        ...       ...
95      Operations      Chris    Garcia
96            None      David   Johnson
97            None       John     Brown
98            None       Jane     Brown
99            None       Jane  Martinez

[100 rows x 3 columns]

# 5 CROSS JOIN
Create a query to show all possible combinations of employee names and department names.

In [ ]:
query = """
SELECT 
    d.department_name, e.first_name, e.last_name
FROM 
    employees AS e
CROSS JOIN 
    departments AS d;
"""

df = pd.read_sql_query(query, conn)

df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/1698066933.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

    department_name first_name last_name
0             Sales       John     Clark
1             Sales       Mike    Garcia
2             Sales      Chris   Johnson
3             Sales       Anna     Brown
4             Sales       Sara  Williams
..              ...        ...       ...
995             R&D      Chris    Garcia
996             R&D      David   Johnson
997             R&D       John     Brown
998             R&D       Jane     Brown
999             R&D       Jane  Martinez

[1000 rows x 3 columns]

# 6 SELF JOIN
Using a self join, write a query to display each employee along with their manager's name. For employees without a manager, display 'No Manager'.

In [23]:
query = """
SELECT
    e.first_name || ' ' || e.last_name AS employee_name,
    CASE WHEN m.first_name IS NOT NULL THEN m.first_name || ' ' || m.last_name
    ELSE 'No Manager' END AS manager_name
FROM
    employees e  -- Alias 'e' for the Employee
LEFT JOIN
    employees m  -- Alias 'm' for the Manager
ON
    e.manager_id = m.employee_id;
"""

df = pd.read_sql_query(query, conn)
# pd.set_option('display.max_rows', None)

df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/3161859804.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

    employee_name   manager_name
0      John Clark     No Manager
1     Mike Garcia     Anna Brown
2   Chris Johnson    John Garcia
3      Anna Brown  Chris Johnson
4   Sara Williams     John Smith
..            ...            ...
95   Chris Garcia  John Williams
96  David Johnson  Sara Williams
97     John Brown     No Manager
98     Jane Brown    Linda Smith
99  Jane Martinez     Anna Brown

[100 rows x 2 columns]

# 7 INNER JOIN with Condition
Select employees whose salary is above the average salary of their department.

In [ ]:
query = """
SELECT
    e.first_name,
    e.last_name,
    e.salary,
    d.department_name
FROM
    employees e
JOIN
    departments d ON e.department_id = d.department_id
WHERE
    e.salary > (
        SELECT AVG(e_sub.salary)
        FROM employees e_sub
        WHERE e_sub.department_id = e.department_id
    );
"""

df = pd.read_sql_query(query, conn)
df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/3629751598.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

   first_name last_name  salary   department_name
0        John     Clark   87362                IT
1       Chris   Johnson   99383                IT
2        John   Johnson  103076             Sales
3       Chris  Martinez  119767               R&D
4       Chris    Garcia  107444               R&D
5       Linda     Smith  105441           Finance
6        Sara  Williams  113698         Marketing
7       David    Garcia   83303                HR
8        John     Brown   99207       Engineering
9       Chris  Williams  115046       Engineering
10      Linda  Williams  113340           Finance
11       John   Johnson  111520               R&D
12      Linda    Garcia  107728             Legal
13       Sara     Smith   85558         Marketing
14      Linda   Johnson  111324                HR
15       Anna  Martinez   99379  Customer Service
16       Mike     Brown  104484         Marketing
17       John     Smith   59029        Operations
18       John    Garcia   99201       Engineering
19      Chris     Smith  111907                IT
20       Sara     Clark  111895       Engineering
21       Jane  Martinez  104772               R&D
22      Chris    Garcia   60609        Operations

# 8 LEFT JOIN with Aggregation
Calculate the average salary for each department. Include departments with no employees, showing a count of 0 and an average salary as 'NULL'.

In [38]:
query = """
SELECT
    d.department_name,
    COUNT(e.employee_id) AS employee_count,
    AVG(e.salary) AS average_salary
FROM
    departments d
LEFT JOIN
    employees e ON d.department_id = e.department_id
GROUP BY
    d.department_name
ORDER BY
    d.department_name;
"""

df = pd.read_sql_query(query, conn)
df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/1572555399.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

    department_name  employee_count  average_salary
0  Customer Service               3    71350.000000
1       Engineering               5    94959.000000
2           Finance               5    84011.600000
3                HR               4    75957.500000
4                IT               6    73997.166667
5             Legal               2    79515.000000
6         Marketing               7    80611.285714
7        Operations               3    58006.666667
8               R&D               5    96747.600000
9             Sales               3    65889.333333

# 9 RIGHT JOIN with Aggregation
Count the number of employees in each department, including departments with no employees. Sort by the number of employees in descending order.

In [40]:
query = """
SELECT
    d.department_name,
    COUNT(e.employee_id) AS employee_count
FROM
    employees e
RIGHT JOIN
    departments d ON e.department_id = d.department_id
GROUP BY
    d.department_name
ORDER BY
    employee_count DESC;
"""

df = pd.read_sql_query(query, conn)
df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/1015146304.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

    department_name  employee_count
0         Marketing               7
1                IT               6
2       Engineering               5
3               R&D               5
4           Finance               5
5                HR               4
6             Sales               3
7        Operations               3
8  Customer Service               3
9             Legal               2

# 10 FULL OUTER JOIN with Advanced Conditions
Write a query to select all employees and department names, including employees without departments and departments without employees. Display a meaningful placeholder for missing data.

In [45]:
query = """
SELECT
    CASE WHEN first_name IS NULL THEN 'No name'
    ELSE first_name || ' ' || last_name END AS employee_name,
    CASE WHEN departments.department_name IS NULL THEN 'No department'
    ELSE departments.department_name END
FROM
    employees
FULL OUTER JOIN
    departments 
ON 
    employees.department_id = departments.department_id;
"""

df = pd.read_sql_query(query, conn)
# pd.set_option('display.max_rows', None)

df

/var/folders/11/_4nf9vcd381d35kpvnpx8jph0000gn/T/ipykernel_243/3139470858.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

    employee_name department_name
0      John Clark              IT
1     Mike Garcia       Marketing
2   Chris Johnson              IT
3      Anna Brown   No department
4   Sara Williams       Marketing
..            ...             ...
95   Chris Garcia      Operations
96  David Johnson   No department
97     John Brown   No department
98     Jane Brown   No department
99  Jane Martinez   No department

[100 rows x 2 columns]


# Submission
Please complete each exercise by writing the corresponding SQL query. Submit your SQL queries as a single document. Upload your completed document to the classroom